#!/usr/bin/env bash

FONT_FAMILY="Terminus"
FONT_SIZE="12"

COLOR_FOREGROUND="#FFC0B18B"
COLOR_BACKGROUND="#FF1F1F1F"

# Lemonbar workspace colors
COLOR_ACTIVE="$COLOR_FOREGROUND"
COLOR_OCCUPIED="#FFAF865A"
COLOR_URGENT="#FFD17B49"
COLOR_FREE="#FF4A3637"

COLOR_LAYOUT_INFO="#FF4A3637"

# Height of underlines / overlines
LINEHEIGHT="2"

# Panel geometry
PANEL_HEIGHT=28
TOP_PADDING=5
SIDE_PADDING=7
PANEL_WIDTH=$(($(xrandr | grep -E '[0-9]+x[0-9]+.*\*' | cut -d x -f1) - $((${SIDE_PADDING} * 2))))
PANEL_GEOMETRY="${PANEL_WIDTH}x${PANEL_HEIGHT}+${SIDE_PADDING}+${TOP_PADDING}"

# Monitor to display panel on
MONITOR="$(bspc query -M | tail -n1)"

# Length of volume bar
BAR_LENGTH=20
BAR_CHAR='='
