#!/usr/bin/env bash

readonly FONT_FAMILY="xos4 Terminus"
readonly FONT_SIZE="12"

readonly COLOR_FOREGROUND="#FFC0B18B"
readonly COLOR_BACKGROUND="#FF1F1F1F"

# Lemonbar workspace colors
readonly COLOR_ACTIVE="$COLOR_FOREGROUND"
readonly COLOR_OCCUPIED="#FFAF865A"
readonly COLOR_URGENT="#FFD17B49"
readonly COLOR_FREE="#FF4A3637"

readonly COLOR_LAYOUT_INFO="#FF4A3637"

# Height of underlines / overlines
readonly LINEHEIGHT="2"

# Panel geometry
readonly PANEL_HEIGHT=28
readonly TOP_PADDING=3
readonly SIDE_PADDING=7
readonly SCREEN_WIDTH=$(xrandr | grep -o "current [0-9]\+ x [0-9]\+" | cut --delimiter=" " --fields=2)
readonly PANEL_WIDTH="$(($SCREEN_WIDTH - ($SIDE_PADDING * 2)))"

readonly PANEL_GEOMETRY="${PANEL_WIDTH}x${PANEL_HEIGHT}+${SIDE_PADDING}+${TOP_PADDING}"

# Monitor to display panel on
MONITOR="$(bspc query -M | tail -n1)"

# Length of volume bar
BAR_LENGTH=20
BAR_CHAR='='
