// Extension for Chrome Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2016 Vlad and Serge Strukoff - All Rights Reserved
chrome.runtime.onStartup.addListener(function(){});
(function(){function l(c){var e={ver:m,nv:3,uid:"",mwvc:!0,color:"yellow",mwvct:0,mwvci:2,gap:10,hq:!0,hqi:"large",pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,hide:!1,ha:!1,anns:!0,cin:!0,cina:!1,cini:2,cinf:!1,cinc:1,cins:"",pt:!1,pti:0,ww:!1,wide:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,h8:!1,a0:!0,a1:!1,a2:!1,a3:!1,a4:!0,a5:!1,ui:0,c0:!1,c1:!1,c2:!1,c3:!1,c4:!1,f0:!0,mrl:!0};a=c;if(void 0===a||null===a||"object"!==typeof a||void 0===a.ver)a={nv:3,uid:s()};for(var b in e)void 0===a[b]&&(a[b]=
e[b]);for(b in a)void 0===e[b]&&(delete a[b],chrome.storage.local.remove(b));for(b in a)typeof a[b]!==typeof e[b]&&(a[b]=e[b]);t();document.cookie&&-1<document.cookie.indexOf("s=1")?(k=parseInt(localStorage.st),u()):(document.cookie="s=1; expires=0; path=/",localStorage.st=k,u(),3==a.nv?v(1):a.ver!==m?(c=k,e=c+10368E5,a.nv=Math.floor(Math.random()*(e-c+1))+c,a.ver=m,h(),setTimeout(n,2317)):0<a.nv&&a.nv<k&&v())}function u(){chrome.runtime.onMessage.addListener(A);a.a0&&a.a3&&B();setTimeout(n,1917)}
function v(c){function e(){chrome.tabs.get(b,function(c){chrome.runtime.lastError||c&&!1==c.active&&chrome.tabs.update(b,{active:!0})})}var b;chrome.tabs.create({url:"http://www.chromeactions.com/"});c?(a.nv=0,h(),p({ea:"install"}),chrome.tabs.create({url:"http://www.hotcleaner.com/clickclean/install-magic.html"},function(c){b=c.id;setTimeout(e,1E3)})):(a.nv=1,h(),p({ea:"update"}),w());setTimeout(n,2112)}function t(c){function e(c){return(Array(8).join("0")+c.toString(16)).slice(-8)}c=chrome.runtime.getURL("");
var b=0,d=0,f=0,g="red LightPink orange lime GreenYellow yellow gold DodgerBlue aqua magenta DeepPink white".split(" ").indexOf(a.color),h="highres hd2880 hd2160 hd1440 hd1080 hd720 large medium small tiny".split(" ").indexOf(a.hqi),b=b|a.h0<<19,b=b|a.h1<<18,b=b|a.h2<<17,b=b|a.h3<<16,b=b|a.h4<<15,b=b|a.h5<<14,b=b|a.h6<<13,b=b|a.h7<<12,b=b|a.h8<<11,b=b|a.a0<<10,b=b|a.a1<<9,b=b|a.a2<<8,b=b|a.a3<<7,b=b|a.a4<<6,b=b|a.a5<<5,b=b|a.c0<<4,b=b|a.c1<<3,b=b|a.c2<<2,b=b|a.c3<<1,b=b|a.c4,d=d|a.ui<<25,d=d|a.wide<<
24,d=d|a.ww<<23,d=d|a.mwvc<<22,d=d|(0>g?4:g)<<18|a.mwvct<<17,d=d|a.mwvci<<15,d=d|a.gap<<10,d=d|a.pause<<9,d=d|a.plist<<8,d=d|a.buf<<7,d=d|a.buf1<<6,d=d|a.loop<<5,d=d|a.hide<<4,d=d|a.ha<<3,d=d|a.anns<<2,d=d|a.pt<<1,d=d|a.pti,f=f|a.mrl<<18,f=f|a.f0<<17,f=f|a.hq<<16,f=f|(0>h?5:h)<<12|a.cin<<11,f=f|a.cina<<10,f=f|a.cini<<8,f=f|a.cinf<<7,f=f|(63<a.cinc?63:a.cinc);c="0"+e(b)+e(d)+e(f)+c+(62<a.cinc?a.cins:"");q='var e=document.createEvent("CustomEvent");e.initCustomEvent("mafy",!1,!1,"'+c+'");window.dispatchEvent(e);if(window.sessionStorage)window.sessionStorage.mafy="'+
c+'"'}function h(){a.a0&&a.a4||(a.ui=0);try{chrome.storage.local.set(a)}catch(c){x(c,1)}try{localStorage.setItem("opt",JSON.stringify(a))}catch(e){x(e,1)}t(1);chrome.tabs.query({windowType:"normal",url:"*://*.youtube.com/*",status:"complete"},function(c){for(var a=0,e=c.length;a<e;a++)chrome.tabs.executeScript(c[a].id,{code:q.replace('"0','"1')})})}function A(c,e,b){if(32==c)return chrome.tabs.executeScript(e.tab.id,{code:q,runAt:"document_start"}),chrome.pageAction.show(e.tab.id),!1;if(c&&6==c.id)return y(c),
!1;try{c=JSON.parse(c)}catch(d){return}0==c.id?b({opt:a,url:e.tab.url}):1==c.id?p(c.ga):2==c.id?chrome.tabs.create({url:c.url,active:!0}):3==c.id?(a=c.opt,h()):4==c.id?(a[c.name]=c.value,h()):5==c.id?b({value:a[c.name]}):6==c.id?y(c.v):7==c.id?w():9==c.id?b(z):11==c.id&&chrome.windows.update(e.tab.windowId,{state:c.v?"fullscreen":"maximized"});return!0}function y(c){z=c;chrome.tabs.query({url:"http://www.chromeactions.com/capture-snapshot-video-frames.html"},function(a){a&&a.length?chrome.tabs.update(a[0].id,
{active:!0},function(){chrome.tabs.sendMessage(a[0].id,c)}):chrome.tabs.create({url:"http://www.chromeactions.com/capture-snapshot-video-frames.html",active:!0})})}function w(){var c="opt.html?s=689"+(new Date).getDate();chrome.tabs.query({url:["http://www.chromeactions.com/magic-options.html",chrome.runtime.getURL("opt.html*")]},function(a){a&&a.length?chrome.tabs.update(a[0].id,{active:!0},function(c){chrome.windows.update(c.windowId,{focused:!0})}):navigator.onLine?C(function(a){chrome.tabs.create({url:a?
"http://www.chromeactions.com/magic-options.html":c,active:!0})}):chrome.tabs.create({url:c,active:!0})})}function C(c){var a=new Image;a.onload=function(){c(1)};a.onerror=function(){c()};a.onabort=function(){c()};a.src="http://www.chromeactions.com/i/1.gif?t="+(new Date).getTime()}function x(a,e){console.log("Magic: "+["Could't read preferences.","Could't write preferences."][e]+" "+a.name+": "+a.message)}function D(a,e){if(7840==a.menuItemId){var b="http://www.youtube.com/results?search_query="+
encodeURIComponent(a.selectionText);0==e.url.indexOf("http://www.youtube.com/")?chrome.tabs.update({url:b}):chrome.tabs.create({url:b,selected:!0})}}function B(){chrome.contextMenus.create({id:"7840",title:"Search YouTube for %s",contexts:["selection"]},function(){chrome.contextMenus.onClicked.addListener(D)})}function n(){r("GET","manifest.json",null,"text",function(a){if(a){try{a=JSON.parse(a)}catch(e){return}r("GET",a.update_url+"?x=id%3Dabjcfabbhafbcdfjoecdgepllmpfceif%26v%3D"+a.version+"%26uc&_="+
(new Date).getTime(),null,"text",function(a){})}})}function p(c){var e=c.ec?c.ec:"app",b=c.ea?c.ea:"unk";c=c.el?c.el:"mafy 6.8.9.9";a.uid||(a.uid=s());r("POST","http://www.google-analytics.com/collect","v=1&tid=UA-326771-7&cid="+a.uid+"&t=event&ec="+e+"&ea="+b+"&el="+c,"text",function(){})}function r(a,e,b,d,f){var g=new XMLHttpRequest;g.open(a,e,!0);d&&(g.responseType=d);g.onload=function(a){200==this.status?f(this.response):f(null)};g.onerror=function(){f(null)};g.onabort=function(){f(null)};g.send(b)}
function s(){var a=Math.random,e=(4294967296*a()>>>0).toString(16),b=((4294967296*a()&4294922239|16384)>>>0).toString(16),d=((4294967296*a()&3221225471|2147483648)>>>0).toString(16),a=(4294967296*a()>>>0).toString(16);8>e.length&&(e=("0000000"+e).slice(-8));8>b.length&&(b=("0000000"+b).slice(-8));8>d.length&&(d=("0000000"+d).slice(-8));8>a.length&&(a=("0000000"+a).slice(-8));return[e,b.slice(0,4),b.slice(4),d.slice(0,4),d.slice(4)+a].join("-")}var m="6.8.9.9",k=Date.now(),z,a,q;chrome.storage.local.get(null,
function(a){if(chrome.runtime.lastError)if(a=localStorage.getItem("opt"),void 0===a)l();else{try{a=JSON.parse(a)}catch(e){a=void 0}l(a)}else l(a)})})();
