#!/usr/bin/env bash

# -Stack Overflow wizerd
# -Round to the nearest integer and add percentage sign
cat <(grep 'cpu ' /proc/stat) <(sleep 1 && grep 'cpu ' /proc/stat) \
    | awk -v RS="" '{print ($13-$2+$15-$4)*100/($13-$2+$15-$4+$16-$5)}' \
    | xargs printf "%.0f%%\n"
