#!/usr/bin/env bash

# -Get all memory information from `free`
# -Grep for the RAM line
# -Divide the used by the total (and multiply by 100 to make a percentage)
# -Round to the nearest integer and add percentage sign
free | grep 'Mem' | awk '{print $3 * 100 / $2}' | xargs printf "%.0f%%\n"
