#!/usr/bin/env bash

# Change to the current directory
cd $(dirname $0)

LOW_BATTERY=false
while true; do
    # Use a short variable name since bash append syntax is clunky
    S="SYS%{B#4A3637} "
    S="${S}CPU: $(./cpu)"
    S="${S} %{F#AF865A}/%{F-} " 
    S="${S}MEM: $(./memory)"
    S="${S} %{F#AF865A}/%{F-} "
    S="${S}BAT: "
    # Actually tell us if the battery is gonna die soon. Revolutionary!
    BATTERY_PERCENT=$(./battery)
    if [ "${BATTERY_PERCENT/\%/}" -le 10 ]; then
        S="${S}%{F#FF0000}"
        if [ "$LOW_BATTERY" = false ]; then
            $HOME/.config/bspwm/panel/popups/alert --text "Low Battery, bruh" --duration 3 &
            LOW_BATTERY=true
        fi
    else
        LOW_BATTERY=false
    fi
    S="${S}$BATTERY_PERCENT "
    S="${S}%{B#AF865A}%{F#4A3637}"
    S="${S} %{A:$HOME/.config/bspwm/panel/popups/calendar:}$(./time)%{A} "
    S="${S}%{F-}%{B-}"
    echo "$S"
    sleep 1
done
