#! /bin/sh

bspc config focus_follows_pointer true
bspc config click_to_focus button1

# Hold alt and use the mouse to fuck with windows.
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config normal_border_color '#AF865A'
bspc config active_border_color '#AF865A'
bspc config focused_border_color '#C0B18B'
bspc config border_width 3
bspc config window_gap   7

bspc config top_padding    31
bspc config bottom_padding 0
bspc config left_padding   0
bspc config right_padding  0

bspc config split_ratio           0.50
bspc config focus_follows_pointer true
bspc config auto_cancel           true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true

# TODO: Change this config depending on whether HDMI1 is connected.
bspc monitor eDP1 -n 0 -d I II III IV V VI VII VIII IX X
#bspc monitor eDP1 -d I II III IV V VI VII
#bspc monitor HDMI1 -d VIII IX X

bspc rule -a "*" state=floating

$HOME/.config/bspwm/autostart
$HOME/.config/bspwm/panel/panel &

