#! /bin/sh

bspc config border_width 4
bspc config window_gap   7

bspc config top_padding    28
bspc config bottom_padding 0
bspc config left_padding   0
bspc config right_padding  0

bspc config split_ratio           0.50
bspc config focus_follows_pointer true
bspc config auto_cancel           true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true

bspc monitor -d eDP1 I II III IV V VI

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/bspwm/autostart
$HOME/.config/bspwm/panel/panel &
