#! /bin/sh

bspc config normal_border_color '#AF865A'
bspc config active_border_color '#AF865A'
bspc config focused_border_color '#C0B18B'
bspc config border_width 3
bspc config window_gap   7

bspc config top_padding    31
bspc config bottom_padding 0
bspc config left_padding   0
bspc config right_padding  0

bspc config split_ratio           0.50
bspc config focus_follows_pointer true
bspc config auto_cancel           true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true

bspc monitor eDP1 -n 0 -d I II III IV V VI VII VIII
bspc monitor HDMI1 -n 1 -d IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/bspwm/autostart
$HOME/.config/bspwm/panel/panel &
