#!/usr/bin/env bash

# Change to the current directory
cd $(dirname $0)

DATE="$(date)"
DAY="$(echo "$DATE" | awk '{print $3}')"
MONTH="$(echo "$DATE" | awk '{print $2}')"

CALENDAR="$(cal)"

IFS=''
newline=$'\n'
result=""
while read line; do
    found=false
    if ! echo "$line" | grep -q '[[:alpha:]]'; then
        IFS=' '
        for number in $line; do
            if [[ $number -eq $DAY ]]; then
                found=true
            fi
        done
        IFS=''
    fi
    
    if [ "$found" = true ]; then
        result="${result}$(echo "$line" | sed "s/$DAY/^bg(#AF865A)^fg(#4A3637) ${DAY} ^fg()^bg()/")${newline}"
    else
        result="${result}${line}${newline}"
    fi
done <<< "$CALENDAR"

# Strip off extra newline
result="$(echo -n "$result")"

./popup --text "$result" --width 200 -x $((1366 - 200 - 7))
