#!/usr/bin/env bash

# Change to the current directory
cd $(dirname $0)

OPTIONS="Options:
    -h, --help   Display  dis.
    -c, -change  How much to change volume (Defaults to \"2%+\")
"

CHANGE="2%+"

while true; do
    case "$1" in
        -h|--help)
            printf "Usage: $(basename $0) [options]\n\n$OPTIONS\n\n"
            exit 1
            ;;
        -c|--change)
            CHANGE="$2"
            shift 2
            ;;
        "")
            break
            ;;
    esac
done

amixer sset Master "$CHANGE" &> /dev/null
VOLUME="$(amixer sget Master "$CHANGE" | egrep -o '\[[0-9]+%\]' | head -1)"
# Strip off left and right brackets
VOLUME=${VOLUME:1:${#VOLUME}-2}
TEXT="Volume: $VOLUME"
echo "$TEXT"

./alert --text "$TEXT" --id "volume"
