#!/usr/bin/env bash

# Change to the current directory
cd $(dirname $0)

OPTIONS="Options:
    -h, --help   Display  dis.
    -c, -change  How much to change volume (Defaults to \"2%+\")
"

CHANGE="2%+"

while true; do
    case "$1" in
        -h|--help)
            printf "Usage: $(basename $0) [options]\n\n$OPTIONS\n\n"
            exit 1
            ;;
        -c|--change)
            CHANGE="$2"
            shift 2
            ;;
        "")
            break
            ;;
    esac
done


VOLUME="$(amixer sset Master playback "$CHANGE" | grep -o '\([0-9]\)\{1,2\}%')"
TEXT="Volume: ${VOLUME}"

./alert --text "$TEXT"
